### ISSUE TITLE
Clearing states for MT_SERGEANT does not result in any free states

### ISSUE THREAD

**Issue by ericabxy** [fragglet/deh9000#7]
**Steps to repeat:**

```
from deh9000 import *
mobjinfo[MT_SERGEANT].clear_states()
dehfile.free_states()
```

**Expected result:**

27 states freed due to clearing SERGEANT state references.

**Actual result:**

None of the states are freed. Results of `mobjinfo[MT_SERGEANT]`

> mobjinfo_t(doomednum=3002, spawnstate=0, spawnhealth=150, seestate=0, seesound=41, reactiontime=8, attacksound=52, painstate=0, painchance=180, painsound=26, meleestate=0, missilestate=0, deathstate=0, xdeathstate=0, deathsound=64, speed=10, radius=1966080, height=3670016, mass=400, damage=0, activesound=77, flags=4194310, raisestate=0)

Results of `dehfile.free_states()`

> {S_DEADBOTTOM, S_STALAG, S_DEADTORSO, S_DSNR1, S_DSNR2}

Results of `mobjinfo[MT_SERGEANT].update` etc.

> deh9000.states_parser.StateRemapException: Can't remap 29 states from old: only have 5 free states to work with.

**Notes**:

I tried this with MT_POSSESSED and MT_FATSO, which resulted in states being freed as expected.

**Comment by fragglet** [comment]
Quick reminder that we use the names from Doom's internal constants, where `MT_SERGEANT` refers to the pinky demon and not the shotgun sergeant. 

So you need to clear the spectre as well (`MT_SHADOWS`) since it uses the same frames. Also the demon corpse (`MT_MISC64`) if you want to be thorough.
